### ISSUE TITLE
Compilation problems and solution

### ISSUE THREAD

**Issue by ekg** [gt1/libmaus2#11]
In attempting to build following the readme, I got:

```
configure.ac:6: error: required file './ltmain.sh' not found
```

I found the solution to be described here http://stackoverflow.com/questions/22603163/automake-error-ltmain-sh-not-found

I have been able to build using:

```
libtoolize
aclocal
autoreconf -i -f
./configure
make
```

**Comment by gt1** [comment]
Thank you for the hint. I have not seen this happen myself, but I have updated the README file.
