### ISSUE TITLE
compilation problem

### ISSUE THREAD

**Issue by estolle** [gt1/libmaus2#12]
Hi there

I wanted ti install biobambam2 and need this libmaus2 for it. I seem to have problems to locally install it as it crashes during the compilation. An admin tried with sudo, also without success.
Any idea what this problem could be?
I am trying to install it on a Linux Cluster (Ubuntu).

...
libtool: link: g++ -O3 -pthread -std=gnu++0x -pthread -fopenmp -rdynamic -o .libs/testlogging test/testlogging.o  ./.libs/libmaus2.so -L/home/estolle/.linuxbrew/Cellar/zlib/1.2.8/lib -L/home/.linuxbrew/Cellar/boost/1.58.0/lib:/usr/lib:usr/local/lib:/usr/include/gsl:/home/programs/htslib_1.2.1/include/htslib:/home/estolle/.linuxbrew/include:/home/programs/beagle/lib -ldl ./.libs/libmaus2_simd_align_128.so ./.libs/libmaus2_simd_align_256.so -lrt -lz -fopenmp -pthread -Wl,-rpath -Wl,/home/programs/libmaus2/lib
depbase=`echo test/testregex.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
    g++ -DHAVE_CONFIG_H -I. -I..   -I/home/.linuxbrew/Cellar/boost/1.58.0/include/boost -I/home/.linuxbrew/Cellar/boost/1.58.0/include/boost  -O3 -pthread  -std=gnu++0x -pthread -fopenmp -MT test/testregex.o -MD -MP -MF $depbase.Tpo -c -o test/testregex.o test/testregex.cpp &&\
    mv -f $depbase.Tpo $depbase.Po
test/testregex.cpp: In function 'void testRegex()':
test/testregex.cpp:25:4: error: '::libmaus2' has not been declared
  ::libmaus2::regex::PosixRegex PR("ab");
    ^
test/testregex.cpp:26:2: error: 'vector' is not a member of 'std'
  std::vector<uint64_t> POS = PR.findAllMatches("abababab");
  ^
test/testregex.cpp:26:22: error: expected primary-expression before '>' token
  std::vector<uint64_t> POS = PR.findAllMatches("abababab");
                      ^
test/testregex.cpp:26:24: error: 'POS' was not declared in this scope
  std::vector<uint64_t> POS = PR.findAllMatches("abababab");
                        ^
test/testregex.cpp:26:30: error: 'PR' was not declared in this scope
  std::vector<uint64_t> POS = PR.findAllMatches("abababab");
                              ^
test/testregex.cpp:28:74: error: 'strlen' was not declared in this scope
 ::cerr << "[" << i << "]=" << POS[i] << " len " << strlen("eeeeeeee") << std::e
                                                                     ^
make[2]: **\* [test/testregex.o] Error 1

**Comment by gt1** [comment]
Hi,

could you retry with the latest release?

**Comment by gt1** [comment]
I think this is fixed by only compiling the regex tests when support for regex was detected by configure.
