### ISSUE TITLE
-march=native in Release builds

### ISSUE THREAD

**Issue by psteinb** [gt1/libmaus2#13]
Hi, as I understand that libmaus2 is meant for building on the host where it is run, it might be a good idea to add "-march=native" to the Release build options if compiled with gcc on linux.
Best

**Comment by gt1** [comment]
Amazingly enough libmaus2 is, at least by it's author, mostly cross compiled for packaging. The release binaries for derived projects (biobambam2, bwtb3m, ...) are supposed to run on x86_64 regardless of additional features, including those which might be present on the build architecture. Nevertheless this might be useful for some users, so I have added the --enabe-native configure option.

**Comment by psteinb** [comment]
Great!

**Comment by gt1** [comment]
See for instance https://github.com/gt1/bwtb3m/releases/tag/0.0.48-release-20160524135941, which is compiled for (not on) Debian Etch to be compatible with a wide range of Linux x86_64 systems.
