### ISSUE TITLE
how to run all tests?

### ISSUE THREAD

**Issue by psteinb** [gt1/libmaus2#14]
Hi, I build libmaus2 and wanted to run all tests on our cluster. How can I do that programmatically? I see a variable `TESTPROGS` in the generated `Makefile`, but AFAIK it's not attached to any target! What am I missing?

**Comment by gt1** [comment]
There is currently no way to run the test programs automatically. Some of them even need special input files not distributed with the library (mainly due to size reasons). I will look into implementing a "make check" target at some point.

**Comment by psteinb** [comment]
Ok, I am glad it's on the roadmap. From my experience, any test that is 
not run regularly (e.g. with every commit) is a dead test. I've had this 
so many times, that I excluded a test from my CI apps/scripts and at 
some point that felt onto my feet.

Best
