### ISSUE TITLE
Increase version number in pkgconfig/libmaus2.pc

### ISSUE THREAD

**Issue by mmokrejs** [gt1/libmaus2#15]
Hi,
  I installed libmaus2 from git but the version number is not >=2.0.225 (at least that is required by biobambam2 from git HEAD as of now):

```
# cat /usr/lib64/pkgconfig/libmaus2.pc
prefix=/usr
exec_prefix=${prefix}
libdir=/usr/lib64
includedir=${prefix}/include

Name: libmaus2
Description: succinct data structures
Requires: zlib   
Version: 2.0.224
Libs: -L${libdir} -lmaus2 -lmaus2_simd_align_128 -lmaus2_simd_align_256  -ldl -fopenmp
Cflags:    -fopenmp  -std=gnu++0x   -I${includedir}
Dllib: -ldl
#
```

Am I right? Thank you.

**Comment by gt1** [comment]
Hi,

the current version number for libmaus2 is 2.0.225 (see https://github.com/gt1/libmaus2/blob/master/configure.ac) . It was updated just recently.

Best,
German

**Comment by mmokrejs** [comment]
Ah, that explains my half-a-day old checkout, thank you. I will re-fetch
