### ISSUE TITLE
Compilation issues

### ISSUE THREAD

**Issue by irenatfh** [gt1/libmaus2#17]
I'm trying to compile a release version of libmaus2 on my Linux machine by simply running the commands 

```
./configure
make
```

as prescribed, but I get a huge number of printouts ending with:

```
make[2]: Leaving directory `/home/ihwang/software/libmaus2-2.0.315-release-20170218132618/src'
Making all in test
make[2]: Entering directory `/home/ihwang/software/libmaus2-2.0.315-release-20170218132618/test'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/home/ihwang/software/libmaus2-2.0.315-release-20170218132618/test'
make[2]: Entering directory `/home/ihwang/software/libmaus2-2.0.315-release-20170218132618'
make[2]: Leaving directory `/home/ihwang/software/libmaus2-2.0.315-release-20170218132618'
make[1]: Leaving directory `/home/ihwang/software/libmaus2-2.0.315-release-20170218132618'
```

Any idea what I'm doing wrong during compilation? I'm happy to paste some of the previous, potentially more informative printouts.

**Comment by gt1** [comment]
The messages you posted do not suggest anything went wrong. Compilation will print out something for every source file in the library, which due to the size of library is a lot. I am happy to have a look at the complete compilation log if you're still concerned.

**Comment by irenatfh** [comment]
Ah, good to know, thanks!
