### ISSUE TITLE
configure does not automatically look for snappy

### ISSUE THREAD

**Issue by mmokrejs** [gt1/libmaus2#19]
Hi,
  I just realized libmaus2 does not use on my system snappy library. From the docs it seems the preferred gzip implementation. But is it better than igzip? Anyway, configure should decide which of the available implementation should be reallu used. User should be able to override configure's decision by say --disable-foo.
  In my hand, unless I explicitly add --with-snappy configure does not even bother to look my snappy headers and lib files. Therefore, I ended up with libmaus2 ignoring my snappy installation.
[config.log.txt](https://github.com/gt1/libmaus2/files/932670/config.log.txt)

**Comment by gt1** [comment]
The default for --with-snappy was no so far. I have changed this to auto detection. I hope this works for you.

**Comment by gt1** [comment]
btw. igzip is only ever used when the gzip level is set to 11 (and the igzip code is present). I would not exactly suggest to use this for production.

**Comment by mmokrejs** [comment]
How about `--with-seqan --with-io_lib --with-lzma --with-gnutls --with-nettle --with-hdf5 --with-gmp --with-fftw`, are they enabled automatically or not?
