### ISSUE TITLE
libmaus2 writes compressed BAM files with 4kB block size killing performance

### ISSUE THREAD

**Issue by mmokrejs** [gt1/libmaus2#20]
Hi,
  I installed biobambam2 on top of libmaus2. In my hands bamsort seems to write files in 4kB chunks, which is too slow on our LustreFS. Could one increase the write blocksize somehow?
  From brief look over the libmaus2 sources it appears to me the following case uses some internal, parallel implementation of gzip inside libmaus2. Due to issue #19 I can confirm libmaus2 was not compiled to use snappy, and I do not have igzip installed. However, I will leave it up to you to find which code path is taken through libmaus2.
```

#! /bin/sh
input_threads=4 # bamsort
output_threads=4 # bamsort

# use 768GB RAM for buffer, still gave me unfortunately disk-based temp file 835GB bamsort_"$hostname"_"$num"_"$num"_bamsort_000000
bamsort SO=coordinate fixmates=1 calmdnm=1 calmdnmreference=hs38DH.fa.gz blockmb=768000 inputthreads=4 outputthreads=4 level=9 index=1 I=input.bam O=output.bam
```

**Comment by gt1** [comment]
libmaus2 uses statfs on Linux to detect the optimal transfer block size, or at least what the file system claims this is.

You can override this by setting the environment variable LIBMAUS2_POSIXFDINPUT_BLOCKSIZE_OVERRIDE .

Try something like

LIBMAUS2_POSIXFDINPUT_BLOCKSIZE_OVERRIDE==2m
export LIBMAUS2_POSIXFDINPUT_BLOCKSIZE_OVERRIDE

The double == is not a typo.

The syntax of the value passed is

prefix_a=blocksize_a:prefix_b=blocksize_b:...

So

LIBMAUS2_POSIXFDINPUT_BLOCKSIZE_OVERRIDE==2m

sets a block size of 2m for the empty file name prefix.

You may consider setting sortthreads=4 as well for bamsort.

**Comment by mmokrejs** [comment]
Hi, thank you for a helpful answer. I went with `LIBMAUS2_POSIXFDINPUT_BLOCKSIZE_OVERRIDE==1m` because our LustreFS uses 1MB stripe size (we have 54 stripes available for this particular filesystem).

Here is what I had before (two examples):
![bamsort_lustrefs_usage__stripe54__112cpus__job621577 isrv5](https://cloud.githubusercontent.com/assets/3297852/25424725/b54db610-2a69-11e7-96c1-e7ade96a345f.png)

![bamsort_lustrefs_usage__stripe54__8cpus__job666489 isrv5](https://cloud.githubusercontent.com/assets/3297852/25424636/498832a2-2a69-11e7-95d1-213bab9b28d2.png)

with `LIBMAUS2_POSIXFDINPUT_BLOCKSIZE_OVERRIDE==1m` I get:
![bamsort_lustrefs_usage__stripe54__8cpus__job688163 isrv5](https://cloud.githubusercontent.com/assets/3297852/25424557/fd00f5cc-2a68-11e7-9baa-d2d37405e457.png)


Please change the defaults to a meaningful value.

Let me translate what our sysadmin wrote:
It is a pity that `LIBMAUS2_POSIXFDINPUT_BLOCKSIZE_OVERRIDE` (`function getPosixFdInputBlockSizeOverride, libmaus2::aio::PosixFdInput::blocksizeoverride`) affects only class `PosixFdInput`.
Regarding statfs, I am not certain author is using it properly but instead is degrading performance. Seems a small change in `getOptimalIOBlockSize` (which is also calling statfs) would be beneficial for many callers from within libmaus2.
Anecdotically, default block size would have been 64k (would `getOptimalIOBlockSize` not kick in). That would have been always better than 4k which was so far.

**Comment by gt1** [comment]
I have changed the block size detection to only use statfs if there is a field f_iosize and 64k otherwise. Note that even if the name LIBMAUS2_POSIXFDINPUT_BLOCKSIZE_OVERRIDE suggests it is only used for input it is in fact also used for output (see https://github.com/gt1/libmaus2/blob/master/src/libmaus2/aio/PosixFdOutputStreamBuffer.hpp#L90 )

**Comment by mmokrejs** [comment]
Probably improving the README for https://github.com/gt1/biobambam2 or even bamsort runtime help would be helpful for other users to get better performance.
