### ISSUE TITLE
Alpine linux and lack of pthread_np

### ISSUE THREAD

**Issue by keiranmraine** [gt1/libmaus2#22]
Is there any way that you are aware of that libmaus2 (and biobambam2) could be modified so that pthread_np isn't needed?

If I try to build on alpine I get the following error:

```
//libmaus-2.0.398-release-20171006110620-src/src/libmaus2/parallel/PosixThread.hpp: In member function 'void libmaus2::parallel::PosixThread::start(const std::vector<long unsigned int>&)':
//libmaus-2.0.398-release-20171006110620-src/src/libmaus2/parallel/PosixThread.hpp:240:70: error: 'pthread_attr_setaffinity_np' was not declared in this scope
      if ( pthread_attr_setaffinity_np(&attr,sizeof(cpu_set_t),&cpuset) )
```

Any ideas?

**Comment by gt1** [comment]
Hi Keiran,

I made some changes to libmaus2 and biobambam2. Could you retry?

Thanks
German

**Comment by keiranmraine** [comment]
testing now

**Comment by keiranmraine** [comment]
Hi German,

I can confirm that it compiles and the commands appear to work.  The re-locatable binaries script you gave me a while back did the build but if I move them they don't work unfortunately:

```
...
Error relocating biobambam/bin/bamtofastq: _ZN8libmaus24util24TempFileRemovalContainer4lockE: symbol not found
Error relocating biobambam/bin/bamtofastq: _ZN8libmaus23aio27InputStreamFactoryContainer9factoriesB5cxx11E: symbol not found
Error relocating biobambam/bin/bamtofastq: _ZN8libmaus24util24TempFileRemovalContainer14tmpdirectoriesB5cxx11E: symbol not found
...
```

Is that a limitation of alpine do you think?

Regardless this is very useful, I can always just link the binaries and leave the data in the initial place.

Thanks,
Keiran

**Comment by gt1** [comment]
Hi Keiran,

do you see any occurence of

-Wl,-z -Wl,origin

in that script?

German

**Comment by keiranmraine** [comment]
Yes for `-Wl`

```
LDFLAGS="-Wl,-rpath=XORIGIN/../lib" ${BUILDDIR}/io_lib-${IOLIBVERSION}-src/configure --prefix=${INSTALLDIR}
```

No for `-z` (other than bash if tests) or lowercase 'origin'.

It's this file (with different versions):

https://github.com/cancerit/dockstore-biobambam2/blob/develop/build/biobambam2-build.sh

**Comment by gt1** [comment]
You could try

replacing

```
LDFLAGS="-Wl,-rpath=XORIGIN/../lib"
```

by

```
LDFLAGS="-Wl,-rpath=XORIGIN/../lib -Wl,-z -Wl,origin"
```

I remember this was necessary for getting the rpath working on some BSD variants, so it may also help for different implementations of libc on Linux.

**Comment by gt1** [comment]
Another note:

the script checks for a certain file type 

```
ELF.*executable
```

before running chrpath on these files. On alpine the produced executable do not match this type, for some reason they are

```
ELF 64-bit LSB shared object
```
Updating this accordinly gives me relocatable binaries.

**Comment by keiranmraine** [comment]
Like this?

```
for i in ${INSTALLDIR}/bin/* ; do
	if [ ! -z `LANG=C file ${i} | egrep "ELF 64-bit LSB shared object" | awk '{print $1}' | perl -p -e "s/://"` ] ; then
		ORIG=`objdump -x ${i} | grep RPATH | awk '{print $2}'`
		MOD=`echo "$ORIG" | sed "s/XORIGIN/\\$ORIGIN/"`
		${TOOLSDIR}/bin/chrpath -r "${MOD}" ${i}
	fi
done
```

I made that and the previous one and it failed after being moved.

**Comment by keiranmraine** [comment]
Found the problem, 'file' wasn't installed, lack of 'set -pipefail' means it wasn't caught.  Working now thanks,
