### ISSUE TITLE
Compilation Failure of libmaus2 on Darwin

### ISSUE THREAD

**Issue by dhall1995** [gt1/libmaus2#23]
Hi,

I have been trying to install libmaus2 on my mac (OS Sierra version 10.12.6) and have been failing at the final `'make install'` command after successfully installing boost and running the configure command 
```
bash configure --prefix=${HOME}/libmaus2 --disable-shared-libmaus2 --disable-asm
	--disable-dependency-tracking
```

When I run `'make install'` the following error is thrown: 

```
libmaus2/lz/ZlibInterface.cpp:274:41: error: no member named 'I386CacheLineSize' in namespace
 'libmaus2::util'
                             reqok = reqok && libmaus2::util::I386CacheLineSize::hasFeature(feature.c_str());
```

I have manually checked the src/libmaus2/util/ and found files I386CacheLineSize.cpp/hpp so I am slightly confused. Is this a known issue?

Thanks!

**Comment by gt1** [comment]
Hi,

could you retry with the latest version?

Best,

**Comment by dhall1995** [comment]
Hi,

Do you mean the latest release or just cloning directly into the main 
development branch?

all the best,

Dominic

**Comment by gt1** [comment]
Hi,

2.0.475-release-20180502124432 should do.

Best,
German

**Comment by dhall1995** [comment]
That's worked. Thanks very much!

all the best,

Dominic
