### ISSUE TITLE
configure fine but make crashes at linking step

### ISSUE THREAD

**Issue by kemin711** [gt1/libmaus2#24]
./.libs/libmaus2.so: undefined reference to `std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::basic_ostringstream(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::_Ios_Openmode)'
./.libs/libmaus2.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::append(char const*)'
./.libs/libmaus2.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find(char, unsigned long) const'
collect2: error: ld returned 1 exit status
make[2]: *** [testAIO] Error 1
make[2]: Leaving directory `/ubilddir/libmaus2-2.0.499-release-20180606122508/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/builddir/libmaus2-2.0.499-release-20180606122508'
make: *** [all] Error 2

Not sure you can help with this one.

**Comment by kemin711** [comment]
There is a very long line of errors, I am only showing the last few line.

**Comment by gt1** [comment]
Could you post some more complete logs? I cannot see much from the snippet provided.

**Comment by gt1** [comment]
Missing feedback, closing.
