### ISSUE TITLE
Difficulties making libmaus2

### ISSUE THREAD

**Issue by PhilippBongartz** [gt1/libmaus2#26]
I'm trying to install libmaus2 to then install Daccord on my mac (MacOS Sierra 10.12.6). Running 'make' seems to run into some problems: There are two kinds of warning, which crop up very often for different files:

./libmaus2/util/Destructable.hpp:44:12: warning: moving a local object in a return statement
      prevents copy elision [-Wpessimizing-move]
                                return UNIQUE_PTR_MOVE(tptr);

In file included from ./libmaus2/aio/StreamLock.hpp:21:
./libmaus2/parallel/PosixSpinLock.hpp:148:26: warning: 'OSSpinLockUnlock' is deprecated:
      first deprecated in macOS 10.12 - Use os_unfair_lock_unlock() from <os/lock.h> instead
      [-Wdeprecated-declarations]
                                OSSpinLockUnlock(&spinlock);

'make' also runs for a pretty long time. (Something like half an hour?)
'make check' results in the following warnings: 

Making check in src
make[1]: Nothing to be done for `check'.
Making check in test
/Applications/Xcode.app/Contents/Developer/usr/bin/make check-TESTS
/bin/sh: ../test-driver: No such file or directory
make[3]: *** [testAIO.sh.log] Error 127
make[2]: *** [check-TESTS] Error 2
make[1]: *** [check-am] Error 2
make: *** [check-recursive] Error 1

I also posted this on your daccord site. Sorry for spamming. Really hope you can help me get daccord to run.

**Comment by gt1** [comment]
Does the actual compilation result in any errors or is it just warnings? Are you trying to compile from a release tarball or directly from the git repository (the failed make check looks like there is an issue with the scripts produced by automake/autoconf)?

**Comment by PhilippBongartz** [comment]
The compilation only results in warnings as far as I can see. I downloaded libmaus2-2.0.499-release-20180606122508. These are the last lines of the 'make' output:

test/testavx.cpp:20:20: warning: unused function 'numString' [-Wunused-function]
static std::string numString(uint64_t const from, uint64_t const to)
                   ^
11 warnings generated.
mv -f test/.deps/testavx-testavx.Tpo test/.deps/testavx-testavx.Po
/bin/sh ../libtool  --tag=CXX   --mode=link g++  -mavx2 -O3  -std=gnu++0x -pthread  -rdynamic -o testavx test/testavx-testavx.o libmaus2.la libmaus2_simd_align_128.la libmaus2_simd_align_256.la  -L/opt/local/lib -lz
libtool: link: g++ -mavx2 -O3 -std=gnu++0x -pthread -rdynamic -o .libs/testavx test/testavx-testavx.o -Wl,-bind_at_load  ./.libs/libmaus2.dylib -L/opt/local/lib ./.libs/libmaus2_simd_align_128.dylib ./.libs/libmaus2_simd_align_256.dylib -lz -pthread
clang: warning: argument unused during compilation: '-pthread' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-pthread' [-Wunused-command-line-argument]
Making all in test
make[2]: Nothing to be done for `all'.

**Comment by gt1** [comment]
The compiled library should be functional, though it is weird that the test scripts do not run (they don't fail their actual contents, they do not even run). You can try running make install and then compile daccord based on that.

**Comment by PhilippBongartz** [comment]
I did do that. And I can run libtool. But when I then try to install daccord, I get the error:

configure: error: Package requirements (libmaus2 >= 2.0.352) were not met:
No package 'libmaus2' found
Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables libmaus2_CFLAGS
and libmaus2_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

This is the reason why I went back to libmaus2 to find out whether there is some kind of issue there. And there was, but maybe it's a separate one.

With daccord maybe the issue is that I try to use the daccord-master file instead of the release. I downloaded both, but in the release I couldn't find an INSTALL or README to guide me through the installation process.
