### ISSUE TITLE
Errors printed by `getAuxAsNumberArray` report themselves as `getAuxAsNumber`

### ISSUE THREAD

**Issue by jrandall** [gt1/libmaus2#6]
The error messages that are printed when exceptions occur during `getAuxAsNumberArray` report themselves as `getAuxAsNumber`. The `called non present tag` message ends up being identical to the one printed by `getAuxAsNumber` so it is difficult to trace which one is reporting the error (https://github.com/gt1/libmaus2/blob/419445c70f14f8d887618ad7c271d898f9f9a468/src/libmaus2/bambam/BamAlignmentDecoderBase.hpp#L2528).

**Comment by gt1** [comment]
I have fixed this in https://github.com/gt1/libmaus2/commit/0e8b6688bc24eddff212b5e8a68fc8d7933982d8 and the fix will appear in the next release.

**Comment by gt1** [comment]
Fixed in version 2.0.90.
